import { test, after } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { Miniflare } from "miniflare";
import { InventoryStore } from "../work/qa/store.mjs";
import { IntakeStore } from "../work/qa/intake-store.mjs";
import { BatteryModelStore } from "../work/qa/battery-model-store.mjs";
import { createExport } from "../work/qa/exports.mjs";
import { filterBatteries } from "../work/qa/inventory-query.mjs";

const mf = new Miniflare({ modules: true, script: "export default {fetch(){return new Response('test')}}", compatibilityDate: "2026-05-15", d1Databases: { DB: "lifecycle-export-tests" }, d1Persist: false });
const db = await mf.getD1Database("DB");
for (const entry of JSON.parse(await readFile("drizzle/meta/_journal.json", "utf8")).entries) await db.batch((await readFile(`drizzle/${entry.tag}.sql`, "utf8")).split("--> statement-breakpoint").filter(sql => sql.trim()).map(sql => db.prepare(sql)));
after(() => mf.dispose());
const at = "2026-10-03T14:30:00.000Z", clock = () => new Date(at);
const actor = { id: "lifecycle-export-staff", displayName: "Lifecycle Staff", role: "staff", authVersion: 1 };
await db.prepare("INSERT INTO staff_accounts(id,username,display_name,role,password_hash,password_salt,hash_iterations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(actor.id, actor.id, actor.displayName, actor.role, "test-only-no-login", "test-only-no-login", 600000, at, at).run();
const store = scope => new InventoryStore(db, scope, "demo", { ...actor, name: actor.displayName }, clock);
const common = { name: "Lifecycle pack", model: "MODEL-A", chemistry: "Li-ion", capacityMah: 3000, voltage: 12, ownerId: `staff-${actor.id}`, homeBuildingId: "J18", homeRoomId: null, manufacturedOn: null, firstUsedOn: null };
const register = (scope, tag, extra = {}) => new IntakeStore(db, scope, "demo", actor, clock).register({ requestId: crypto.randomUUID(), sessionId: crypto.randomUUID(), tagId: `DEMO-INTAKE-${tag}`, scannedAt: "2026-10-03T13:30:00.000Z", common: { ...common, ...extra }, firstUseMode: "at_registration" });
const remove = (s, b, kind) => s.lifecycle({ requestId: crypto.randomUUID(), kind, reason: "Removed from service", destination: kind === "permanently_removed" ? "External transfer" : null, source: "manual_selection", items: [{ batteryId: b.id, tagId: b.tagId, version: b.version }] });

test("staff retirement preserves full identity and evidence while filters, summaries and selected details distinguish terminal records", async () => {
    const scope = "lifecycle-export", s = store(scope);
    const a = await register(scope, "ACTIVE"), b = await register(scope, "SCRAP"), c = await register(scope, "REMOVE");
    await remove(s, (await s.detail(b.batteryId)).battery, "scrapped");
    await remove(s, (await s.detail(c.batteryId)).battery, "permanently_removed");
    const snapshot = await s.snapshot();
    assert.equal(snapshot.batteries.length, 3);
    assert.deepEqual(filterBatteries(snapshot.batteries, {}).map(battery => battery.id), [a.batteryId]);
    assert.deepEqual(filterBatteries(snapshot.batteries, { lifecycle: "all", status: "in" }).map(battery => battery.id), [a.batteryId]);
    assert.deepEqual(filterBatteries(snapshot.batteries, { lifecycle: "scrapped" }).map(battery => battery.id), [b.batteryId]);
    const standard = await createExport(s, { dataset: "demo", mode: "summary" });
    assert.equal(standard.tables.Inventory.length, 1);
    const archived = await createExport(s, { dataset: "demo", mode: "summary", filter: { lifecycle: "all" } });
    assert.equal(archived.tables.Inventory.find(row => row.battery_id === b.batteryId).status, "Scrapped");
    assert.equal(archived.tables.Inventory.find(row => row.battery_id === c.batteryId).lifecycle_destination, "External transfer");
    const selected = await createExport(s, { dataset: "demo", mode: "detail", range: "selected", batteryIds: [b.batteryId, c.batteryId], filter: { personalScope: "responsible", lifecycle: "all" } });
    assert.equal(selected.tables.Batteries.length, 2);
    assert.ok(selected.tables.Batteries.every(row => row.created_at === at && row.registered_at_utc === at && row.lifecycle_reason === "Removed from service"));
    const events = selected.tables.Operations.map(row => ({ ...row, details: JSON.parse(row.details_json) }));
    assert.ok(events.some(event => event.action === "battery_scrapped" && event.actor_id === actor.id && event.details.reviewedBinding.batteryId === b.batteryId));
    assert.ok(events.some(event => event.action === "battery_permanently_removed" && event.details.destination === "External transfer" && event.details.before.ownerAccountId === actor.id));
    assert.ok(events.filter(event => event.action === "battery_registered").every(event => event.details.scannedAt === "2026-10-03T13:30:00.000Z" && event.details.scanTimeSource === "client_demo_draft"));
    const single = await createExport(s, { dataset: "demo", mode: "detail", batteryId: b.batteryId, sections: ["specifications", "audit"] });
    assert.equal(single.tables.Batteries[0].lifecycle_status, "scrapped");
});
test("retiring an original inventory model source stops stale intake while archived tags and IDs remain reserved", async () => {
    const scope = "lifecycle-model-guard", s = store(scope);
    const original = await register(scope, "MODEL-SOURCE");
    const choice = (await new BatteryModelStore(db, scope, "demo", actor, clock).list()).models.find(model => model.origin === "inventory");
    const sessionId = crypto.randomUUID(), configured = { ...common, modelSelection: { origin: "inventory", id: choice.id, contentHash: choice.contentHash, confirmed: true, appliedFields: ["model", "chemistry", "capacityMah", "voltage"] } };
    const intake = new IntakeStore(db, scope, "demo", actor, clock);
    await intake.register({ requestId: crypto.randomUUID(), sessionId, tagId: "DEMO-INTAKE-MODEL-FIRST", common: configured, firstUseMode: "at_registration" });
    await remove(s, (await s.detail(original.batteryId)).battery, "scrapped");
    await assert.rejects(intake.register({ requestId: crypto.randomUUID(), sessionId, tagId: "DEMO-INTAKE-MODEL-SECOND", common: configured, firstUseMode: "at_registration" }), error => error.status === 409 && error.code === "intake_rejected_final");
    await assert.rejects(register(scope, "MODEL-SOURCE"), error => error.status === 409 && error.code === "intake_rejected_final");
    assert.equal((await s.snapshot()).batteries.length, 2);
    assert.equal((await s.detail(original.batteryId)).battery.tagId, "DEMO-INTAKE-MODEL-SOURCE");
});
