"use client";
import { useEffect, useState } from "react";
import { Battery, Package, Search, Plus, Download, Upload, Pencil, Settings2, ClipboardList } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import type { InventorySnapshot, AuditEvent } from "@/lib/domain";
import type { EditorDraft } from "./record-editor";
import { actionNames, formatTime, buildingLabel, roomLabel, storageRoomLabel, durationLabel } from "@/lib/client-utils";
import { filterBatteries, type InventoryFilter } from "@/lib/inventory-query";
import type { ExportDraft } from "./export-dialog";
import type { ExportDocument } from "@/lib/exports";
async function downloadList(dataset: string, mode: string, search: string, kind?: string) {
    const response = await fetch("/api/export", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dataset, mode, search, kind }) });
    const body = await response.json() as ExportDocument & { error?: string };
    if (!response.ok) throw new Error(body.error || "The download could not be prepared.");
    const link = document.createElement("a");
    link.href = `/api/export?${new URLSearchParams({ request: JSON.stringify({ dataset, mode, search, kind }), format: "csv" })}`;
    document.body.appendChild(link); link.click(); link.remove();
}
export type ImportKind = "people" | "buildings" | "rooms" | "batteries";
type RecordActions = {
    data: InventorySnapshot;
    ready: boolean;
    onEdit: (draft: EditorDraft) => void;
    onDetail: (id: string) => void;
};
export function InventoryTable({ data, ready, onMovement, onEdit, onDetail, onSetup, onExport }: RecordActions & {
    onMovement: (kind: "checkout" | "return", ids: string[]) => void;
    onSetup: () => void;
    onExport: (draft: ExportDraft) => void;
}) {
    const [filter, setFilter] = useState("all"), [building, setBuilding] = useState("all"), [room, setRoom] = useState("all"), [search, setSearch] = useState("");
    const [selected, setSelected] = useState<string[]>([]);
    const [owner, setOwner] = useState("all"), [page, setPage] = useState(0), [pageSize, setPageSize] = useState<"10" | "25" | "50" | "100">("25");
    const batteries = data.batteries, onLoan = batteries.filter(b => b.loanId).length;
    const filters: InventoryFilter = { status: filter as InventoryFilter["status"], building, room, owner, search };
    const matching = filterBatteries(batteries, filters);
    const pageCount = Math.max(1, Math.ceil(matching.length / Number(pageSize))), currentPage = Math.min(page, pageCount - 1);
    const visible = matching.slice(currentPage * Number(pageSize), (currentPage + 1) * Number(pageSize));
    function selectAll(checked: boolean) { setSelected(checked ? [...new Set([...selected, ...visible.map(b => b.id)])] : selected.filter(id => !visible.some(b => b.id === id))); }
    function exportInventory() { onExport({ filter: filters, page: currentPage, pageSize, matching: matching.length, pageCount: visible.length }); }
    return <><div className="summary-grid">{[["Registered batteries", batteries.length, "Across registered storage locations"], ["In store", batteries.length - onLoan, "No active loan recorded"], ["On loan", onLoan, "Linked to a current borrower"]].map(([label, count, note]) => <div className="summary-card" key={label}><span>{label}</span><strong>{count}</strong><p>{note}</p></div>)}</div>
    <section className="inventory-panel" aria-label="Battery inventory records"><div className="panel-top"><Tabs value={filter} onValueChange={value => { setFilter(value); setPage(0); }}><TabsList variant="line"><TabsTrigger value="all">All batteries <span className="tab-count">{batteries.length}</span></TabsTrigger><TabsTrigger value="in">In store <span className="tab-count">{batteries.length - onLoan}</span></TabsTrigger><TabsTrigger value="out">On loan <span className="tab-count">{onLoan}</span></TabsTrigger></TabsList></Tabs><Button variant="outline" onClick={() => onEdit({ kind: "battery" })} disabled={!ready}><Plus />Register battery</Button></div>
    <div className="table-toolbar"><div className="search-field"><Search size={18}/><Input aria-label="Search batteries" placeholder="Search batteries, people or location…" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }}/></div><Select value={building} onValueChange={v => { setBuilding(v); setRoom("all"); setPage(0); }}><SelectTrigger aria-label="Filter by storage building" className="room-filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All buildings</SelectItem>{data.buildings.map(b => <SelectItem key={b.id} value={b.id}>{buildingLabel(b)}</SelectItem>)}</SelectContent></Select><Select value={room} onValueChange={value => { setRoom(value); setPage(0); }}><SelectTrigger aria-label="Filter by registered storage room" className="room-filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All storage rooms</SelectItem><SelectItem value="__unspecified">Room not specified</SelectItem>{data.rooms.filter(r => building === "all" || r.buildingId === building).map(r => <SelectItem key={r.id} value={r.id}>{building === "all" && r.buildingId ? `${r.buildingId} / ` : ""}{roomLabel(r)}</SelectItem>)}</SelectContent></Select><Select value={owner} onValueChange={value => { setOwner(value); setPage(0); }}><SelectTrigger aria-label="Filter by responsible owner" className="room-filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All responsible owners</SelectItem>{data.people.filter(person => person.role === "staff").map(person => <SelectItem key={person.id} value={person.id}>{person.name}</SelectItem>)}</SelectContent></Select><Button variant="ghost" onClick={exportInventory} disabled={!matching.length} aria-label="Export filtered inventory"><Download size={16}/><span>Download</span></Button><span className="toolbar-meta">{matching.length} batteries</span></div>
    {!!selected.length && <div className="selection-toolbar"><strong>{selected.length} selected</strong><Button variant="outline" size="sm" onClick={() => onMovement("checkout", selected)} disabled={!ready || selected.some(id => batteries.find(b => b.id === id)?.loanId)}>Check out selected</Button><Button variant="outline" size="sm" onClick={() => onMovement("return", selected)} disabled={!ready || selected.some(id => !batteries.find(b => b.id === id)?.loanId)}>Return selected</Button><Button variant="ghost" size="sm" onClick={() => setSelected([])}>Clear selection</Button></div>}
    <Table><TableHeader><TableRow><TableHead className="checkbox-cell"><Checkbox aria-label="Select all batteries on this page" checked={visible.length > 0 && visible.every(b => selected.includes(b.id)) ? true : visible.some(b => selected.includes(b.id)) ? "indeterminate" : false} disabled={!visible.length || !ready} onCheckedChange={v => selectAll(v === true)}/></TableHead><TableHead>BATTERY</TableHead><TableHead>STATUS</TableHead><TableHead>RESPONSIBLE OWNER</TableHead><TableHead>CURRENT BORROWER</TableHead><TableHead>STORAGE LOCATION</TableHead><TableHead>LAST OBSERVED</TableHead></TableRow></TableHeader><TableBody>{visible.map(b => <TableRow key={b.id} data-selected={selected.includes(b.id)}><TableCell className="checkbox-cell"><Checkbox aria-label={`Select ${b.id}`} checked={selected.includes(b.id)} disabled={!ready} onCheckedChange={v => setSelected(s => v ? [...s, b.id] : s.filter(id => id !== b.id))}/></TableCell><TableCell><div className="battery-cell"><span className="battery-icon"><Battery size={19}/></span><div><button className="record-link" onClick={() => onDetail(b.id)} aria-label={`View ${b.id}`}>{b.id}</button><span>{b.name}</span><small>{b.chemistry || "Chemistry not recorded"}{b.capacityMah != null ? ` · ${b.capacityMah.toLocaleString()} mAh` : ""}</small></div></div></TableCell><TableCell><span className={`status-badge ${b.loanId ? "out" : "in"}`}>{b.loanId ? "On loan" : "In store"}</span></TableCell><TableCell>{b.ownerName}</TableCell><TableCell>{b.borrowerName || <span className="muted">—</span>}</TableCell><TableCell><strong>{b.homeBuildingId ? buildingLabel({ id: b.homeBuildingId, name: b.homeBuildingName! }) : "Building not assigned"}</strong><span className="cell-secondary">{storageRoomLabel(b)}</span></TableCell><TableCell>{b.observedAt ? <><strong>{b.observedRoom}</strong>{b.observedBuilding && <span className="cell-secondary">{b.observedBuilding}</span>}<span className="cell-secondary">{formatTime(b.observedAt)}</span><span className="cell-secondary">{b.observationSource}</span></> : <span className="muted">Not yet observed</span>}</TableCell></TableRow>)}</TableBody></Table>
    {!matching.length && <div className="empty-state"><Package /><h3>{batteries.length ? "No matching batteries" : "No batteries registered"}</h3><p>{batteries.length ? "Adjust the search, status or location filters." : "Register a staff owner, then add a battery in J18. Its room can stay unspecified."}</p>{!batteries.length && <Button variant="outline" onClick={onSetup}>Set up records</Button>}</div>}
    <div className="pagination-bar"><span>{matching.length ? currentPage * Number(pageSize) + 1 : 0}–{Math.min((currentPage + 1) * Number(pageSize), matching.length)} of {matching.length} matching batteries</span><div><Select value={pageSize} onValueChange={value => { setPageSize(value as typeof pageSize); setPage(0); }}><SelectTrigger aria-label="Batteries per page"><SelectValue /></SelectTrigger><SelectContent>{["10", "25", "50", "100"].map(size => <SelectItem key={size} value={size}>{size} per page</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" onClick={() => setPage(currentPage - 1)} disabled={!currentPage}>Previous</Button><span>Page {currentPage + 1} of {pageCount}</span><Button variant="outline" size="sm" onClick={() => setPage(currentPage + 1)} disabled={currentPage >= pageCount - 1}>Next</Button></div></div>
    <div className="panel-footer"><span>Storage building and room are the registered home. Last observed location is separate, dated evidence.</span><span>{batteries.length} registered batteries</span></div></section>
  </>;
}
export function RecordManagement({ data, ready, onEdit, onDetail, onImport }: RecordActions & {
    onImport: (kind: ImportKind) => void;
}) {
    const [kind, setKind] = useState<ImportKind>("people");
    const [query, setQuery] = useState(""), [downloadError, setDownloadError] = useState("");
    const admin = data.user.role === "admin";
    const records = (kind === "people" ? data.people : kind === "buildings" ? data.buildings : kind === "rooms" ? data.rooms : data.batteries).filter(record => Object.values(record).join(" ").toLowerCase().includes(query.toLowerCase()));
    const people = data.people.filter(person => records.some(record => record.id === person.id));
    const buildings = data.buildings.filter(building => records.some(record => record.id === building.id));
    const rooms = data.rooms.filter(room => records.some(record => record.id === room.id));
    const batteries = data.batteries.filter(battery => records.some(record => record.id === battery.id));
    const editorKind = kind === "people" ? "person" : kind === "buildings" ? "building" : kind === "rooms" ? "room" : "battery";
    return <section className="inventory-panel"><div className="panel-top"><Tabs value={kind} onValueChange={v => setKind(v as ImportKind)}><TabsList variant="line"><TabsTrigger value="people">People</TabsTrigger><TabsTrigger value="buildings">Buildings</TabsTrigger><TabsTrigger value="rooms">Rooms</TabsTrigger><TabsTrigger value="batteries">Batteries</TabsTrigger></TabsList></Tabs><div className="panel-actions">{(admin || kind === "batteries") && <><Button variant="outline" onClick={() => onImport(kind)} disabled={!ready}><Upload />Import CSV</Button><Button onClick={() => onEdit({ kind: editorKind })} disabled={!ready}><Plus />Register {editorKind}</Button></>}</div></div><div className="table-toolbar"><Input aria-label="Search managed records" placeholder="Search these records…" value={query} onChange={event => setQuery(event.target.value)}/><Button variant="outline" disabled={!records.length} onClick={() => downloadList(data.dataset, "records", query, kind).catch(error => setDownloadError(error.message))}><Download size={16}/>Download filtered list</Button><span>{records.length} records</span></div>{downloadError && <p className="form-error" role="alert">{downloadError}</p>}
    {kind === "people" ? <Table><TableHeader><TableRow><TableHead>PERSON</TableHead><TableHead>REFERENCE</TableHead><TableHead>RECORD ROLE</TableHead>{admin && <TableHead>ACTIONS</TableHead>}</TableRow></TableHeader><TableBody>{people.map(p => <TableRow key={p.id}><TableCell><strong>{p.name}</strong><span className="cell-secondary">{p.id}</span></TableCell><TableCell>{p.reference || "Not recorded"}</TableCell><TableCell>{p.role === "staff" ? "Staff / responsible owner" : "Borrower"}</TableCell>{admin && <TableCell><Button variant="ghost" size="sm" onClick={() => onEdit({ kind: "person", record: p })} disabled={!ready} aria-label={`Edit ${p.name}`}><Pencil />Edit</Button></TableCell>}</TableRow>)}</TableBody></Table> : kind === "buildings" ? <Table><TableHeader><TableRow><TableHead>BUILDING CODE</TableHead><TableHead>NAME</TableHead>{admin && <TableHead>ACTIONS</TableHead>}</TableRow></TableHeader><TableBody>{buildings.map(b => <TableRow key={b.id}><TableCell><strong>{b.id}</strong></TableCell><TableCell>{b.name}</TableCell>{admin && <TableCell><Button variant="ghost" size="sm" onClick={() => onEdit({ kind: "building", record: b })} disabled={!ready} aria-label={`Edit ${b.id}`}><Pencil />Edit</Button></TableCell>}</TableRow>)}</TableBody></Table> : kind === "rooms" ? <Table><TableHeader><TableRow><TableHead>ROOM</TableHead><TableHead>BUILDING</TableHead>{admin && <TableHead>ACTIONS</TableHead>}</TableRow></TableHeader><TableBody>{rooms.map(r => <TableRow key={r.id}><TableCell><strong>{roomLabel(r)}</strong><span className="cell-secondary">{r.id}</span></TableCell><TableCell>{r.buildingId ? r.building : "Building not assigned"}{!r.buildingId && r.building && <span className="cell-secondary">Legacy label: {r.building}</span>}</TableCell>{admin && <TableCell><Button variant="ghost" size="sm" onClick={() => onEdit({ kind: "room", record: r })} disabled={!ready} aria-label={`Edit ${r.name}`}><Pencil />Edit</Button></TableCell>}</TableRow>)}</TableBody></Table> : <Table><TableHeader><TableRow><TableHead>BATTERY</TableHead><TableHead>RFID IDENTIFIER</TableHead><TableHead>OWNER / STORAGE LOCATION</TableHead>{admin && <TableHead>ACTIONS</TableHead>}</TableRow></TableHeader><TableBody>{batteries.map(b => <TableRow key={b.id}><TableCell><button className="record-link" onClick={() => onDetail(b.id)}>{b.id}</button><span className="cell-secondary">{b.name}</span></TableCell><TableCell>{b.tagId || "Not assigned"}</TableCell><TableCell>{b.ownerName}<span className="cell-secondary">{b.homeBuildingId || "Building not assigned"} / {storageRoomLabel(b)}</span></TableCell>{admin && <TableCell><Button variant="ghost" size="sm" onClick={() => onEdit({ kind: "battery", record: b })} disabled={!ready} aria-label={`Edit ${b.id}`}><Pencil />Edit</Button></TableCell>}</TableRow>)}</TableBody></Table>}
    {!records.length && <div className="empty-state"><Settings2 /><h3>No {kind} registered</h3><p>{admin || kind === "batteries" ? "Use the registration form or review a CSV import." : "Ask an administrator to register these records."}</p></div>}
    <div className="panel-footer"><span>{kind === "buildings" || kind === "rooms" ? "J18 is the initial target. Register only confirmed rooms; a battery's room can remain unspecified." : "People are inventory records. Staff own batteries; registered people can borrow them."}</span></div>
  </section>;
}
export function ActivityHistory({ data, onDetail }: { data: InventorySnapshot; onDetail: (id: string) => void }) {
    const [events, setEvents] = useState<AuditEvent[]>(data.events), [query, setQuery] = useState(""), [error, setError] = useState(""), [page, setPage] = useState(0);
    useEffect(() => {
        const abort = new AbortController();
        fetch(`/api/inventory?dataset=${data.dataset}&activity=all`, { signal: abort.signal, cache: "no-store" }).then(async response => { const body = await response.json() as { error?: string; events: AuditEvent[] }; if (!response.ok) throw new Error(body.error); setEvents(body.events); setError(""); }).catch(error => { if (error.name !== "AbortError") setError(error.message); });
        return () => abort.abort();
    }, [data.dataset, data.events]);
    const matching = events.filter(event => `${event.action} ${event.batteryId ?? ""} ${event.actorName} ${JSON.stringify(event.details)} ${event.at}`.toLowerCase().includes(query.toLowerCase())), maxPage = Math.max(0, Math.ceil(matching.length / 25) - 1), currentPage = Math.min(page, maxPage);
    return <section className="inventory-panel"><div className="section-heading"><h2>Recorded activity</h2><span className="toolbar-meta">{matching.length} matching events · Sydney time</span></div><div className="table-toolbar"><Input aria-label="Search activity" placeholder="Search battery, operator or action…" value={query} onChange={event => { setQuery(event.target.value); setPage(0); }}/><Button variant="outline" disabled={!matching.length} onClick={() => downloadList(data.dataset, "activity", query).catch(error => setError(error.message))}><Download size={16}/>Download filtered history</Button></div>{error && <p className="form-error" role="alert">{error}</p>}<Table><TableHeader><TableRow><TableHead>ACTION / DETAILS</TableHead><TableHead>BATTERY</TableHead><TableHead>OPERATOR</TableHead><TableHead>RECORDED AT</TableHead></TableRow></TableHeader><TableBody>{matching.slice(currentPage * 25, (currentPage + 1) * 25).map(event => <TableRow key={event.id}><TableCell><strong>{actionNames[event.action] ?? event.action}</strong><EventDescription event={event}/></TableCell><TableCell>{event.batteryId ? <button className="record-link" onClick={() => onDetail(event.batteryId!)}>{event.batteryId}</button> : "—"}</TableCell><TableCell>{event.actorName}</TableCell><TableCell>{formatTime(event.at)}</TableCell></TableRow>)}</TableBody></Table>{!matching.length && <div className="empty-state"><ClipboardList /><h3>No matching activity</h3><p>Try another search, or record a confirmed operation.</p></div>}<div className="pagination-bar"><span>{matching.length} matching events</span><div><Button variant="outline" size="sm" disabled={!currentPage} onClick={() => setPage(currentPage - 1)}>Previous</Button><span>Page {currentPage + 1} of {maxPage + 1}</span><Button variant="outline" size="sm" disabled={currentPage >= maxPage} onClick={() => setPage(currentPage + 1)}>Next</Button></div></div><div className="panel-footer">The search and download cover the complete stored history. Corrections retain the original action.</div></section>;
}
function EventDescription({ event }: {
    event: AuditEvent;
}) {
    const d = event.details, after = d.after as {
        id?: string;
        name?: string;
    } | undefined;
    const text = typeof d.reason === "string" ? `Reason: ${d.reason}` : typeof d.borrower === "string" ? `Borrower: ${d.borrower}` : event.action === "records_imported" ? `${d.count} ${d.kind} imported` : typeof d.room === "string" ? `${d.room} · ${d.source}` : event.action === "charge_recorded" ? `Completed ${formatTime(String(d.completedAt))} · ${durationLabel(typeof d.durationMinutes === "number" ? d.durationMinutes : null)}` : after?.name ? `${after.name} · ${after.id}` : typeof d.note === "string" ? d.note : "";
    return text ? <span className="cell-secondary">{text}</span> : null;
}
