"""v0.3 typing contracts. No backend, model or business implementation is provided."""
from __future__ import annotations
from typing import Any, Protocol

JSON = dict[str, Any]

class ModelPort(Protocol):
    async def probe(self) -> JSON: ...
    async def generate(self, request: JSON) -> JSON: ...
    async def cancel(self, run_id: str) -> None: ...

class EvidencePort(Protocol):
    async def search(self, query: str, scope: JSON) -> JSON: ...
    async def read(self, evidence_id: str, revision: str, context: JSON) -> JSON: ...

class StatePort(Protocol):
    async def read_case(self, case_id: str, revision: int | None, context: JSON) -> JSON: ...
    async def read_assets(self, asset_ids: list[str], as_of: str | None, context: JSON) -> JSON: ...

class PredictorPort(Protocol):
    async def describe(self) -> JSON: ...
    async def run(self, method_id: str, request: JSON) -> JSON: ...

class BusinessActionPort(Protocol):
    async def describe_capabilities(self) -> JSON: ...
    async def preview(self, request: JSON, context: JSON) -> JSON: ...
    # No executable submit/approve/physical-control capability is enabled in v0.3.
