import json,pathlib,collections,datetime,re
RUN=pathlib.Path(__file__).resolve().parents[1];OUT=pathlib.Path(__file__).parent;READY=pathlib.Path(r'E:\desn 2000\bsc\data_preparation\CR-DATA-READY-001\20260920T012405_AEST')
def rows(p):return [json.loads(s) for s in p.read_text(encoding='utf-8-sig').splitlines() if s]
scope=[x for x in rows(RUN/'CANDIDATE_SCOPE.jsonl') if x.get('lane')=='review_restricted'];ids={x['fact_id'] for x in scope};cs={x['fact_id']:x for x in rows(OUT/'CANDIDATES_DETAIL.jsonl')};ss={x['file_id']:x for x in rows(RUN/'SOURCE_SCOPE.jsonl')}
cont={'A0033':'INR18650-P28A','A0035':'INR18650-P28B','A0038':'INR18650-M35A','A0044':'INR21700-P45B','A0046':'INR21700-M50A'}
res=[];ctx=[]
for fid in sorted(ids):
 c=cs[fid];file=c['file_id'];p=pathlib.Path(ss[file]['source']['input_path']);page=int(c['locator'].split(':')[1].split('/')[0]);suffix=fid.rsplit('-',1)[-1];ready=False;unknown=[]
 refs=[f'{p}#page={page}',str(RUN/'rights_review/ACTION_REVIEW.json')+'#file_id='+file,c['evidence_ref']]
 entity={'file_id':file,'document_version':ss[file]['source']['document_version_id']}
 if '5466376' in file:
  entity['document']='E-One Moli Energy SDS FSSF00058BJ';entity['revision']='BJ / January 2025'
  if suffix in ('A0002','A0008'):
   role='HAZCHEM_EMERGENCY_ACTION_CODE';qb=[{'value_text':'4W','unit':None,'binding':'Hazchem code','parser_correction':'4W is an alphanumeric emergency action code, not four watts.'}];find=['The token is labeled as the Hazchem code in fire-fighting/transport context.'];cond=['Applies as the SDS-listed Hazchem code for jurisdictions named by the source; not an electrical power value or universal response instruction.'];ready=False
  elif suffix=='A0005':
   role='TABLE_HEADER_CONDITION_NOT_VALUE';qb=[{'value_text':'20','unit':'°C','binding':'temperature condition embedded in vapor-pressure column label','parameter_value':False}];find=['20 °C belongs to the vapor-pressure property heading; the corresponding sealed-cell value is not applicable.'];cond=['Physical/chemical properties table for sealed, contained, uncompromised cells/batteries; footnote applies.'];ready=False
  elif suffix=='A0006':
   role='SDS_PHYSICAL_PROPERTY';qb=[{'entity':'decomposition temperature','value_text':'90','unit':'°C'}];find=['90 °C is the decomposition-temperature entry, distinct from the not-applicable auto-ignition entry.'];cond=['SDS physical-properties table; footnote says information is based on sealed, contained, uncompromised cells/batteries.'];ready=True
  elif suffix=='A0007':
   role='SDS_CONDITION_TO_AVOID';qb=[{'entity':'fire/temperature exposure to avoid','relation':'>','value_text':'80','unit':'°C'}];find=['The value occurs under Conditions to avoid, alongside fire and abuse prohibitions.'];cond=['Manufacturer SDS handling/stability warning for covered cells/batteries; not a validated operating limit or case-specific approval.'];ready=True
  elif suffix in ('A0009','A0010','A0011'):
   name={'A0009':'Copper','A0010':'Manganese','A0011':'Nickel'}[suffix];m=c['numeric_unit_mentions'][0];role='SDS_REGULATORY_COMPOSITION_RANGE';qb=[{'entity':name,'range_text':m['value_text'],'unit':'% w/w'}];find=['The range is a percent-by-weight regulatory composition disclosure, not state of charge or performance.'];cond=['Bound to the January 2025 SDS regulatory-information section for products covered by that SDS.'];ready=True
  else:
   role='SDS_MODEL_SPECIFICATION_TABLE_ROW';literal=c['source_literal'];model=cont.get(suffix) or literal.split()[0];qb=[]
   for m in c['numeric_unit_mentions']:
    unit=m['unit'].replace('��','°');qb.append({'value_text':m['value_text'],'unit':unit,'binding':'Table 6 column context; preserve typical/minimum qualifiers from row continuation'})
   find=['Candidate belongs to Table 6 for cell/pack capacities and watt-hour ratings; columns are model, nominal voltage, typical/minimum capacity, watt-hour rating, equivalent lithium content, and weight.','Apparent small gram values before final weight are equivalent-lithium-content values, not cell mass.']
   cond=[f'Model-specific record for {model}; January 2025 SDS revision BJ.','Parenthesized values marked Min are minimum capacity/energy; unparenthesized values follow the table header semantics.','This SDS table is not a universal battery limit or proof of current product availability.'];entity['model']=model;ready=True
 elif '7ae372' in file:
  role='CERTIFICATE_ISSUER_ADDRESS_TOKEN';qb=[{'value_text':'5A','unit':None,'binding':'street address Borupvang 5A','parameter_value':False,'parser_correction':'Not five amperes.'}];find=['5A is part of the selected issuing body street address, not an electrical rating.'];cond=['Certificate identifies UL (Demko) as issuing NCB and is dated 2022-04-26.','Certificate scope is INR-21700-P42A and listed IEC/EN 62133-2 editions; no inference of current validity, UNSW approval, or other models.'];entity.update({'document':'IECEE CB Test Certificate','certificate_number':'DK-126851-UL','model':'INR-21700-P42A'});ready=False
 else:
  role='P42A_V1_7_DATASHEET_PARAMETER';entity.update({'document':'INR-21700-P42A product data sheet','model':'INR-21700-P42A','document_version':'1.7','registered_document_version_id':ss[file]['source']['document_version_id']});m=c['numeric_unit_mentions']
  mapping={'A0002':('typical energy','15.5','Wh','Typical'), 'A0004':('minimum energy','14.7','Wh','Minimum'),'A0011':('DC impedance','16','mΩ','measured at 10 A for 1 s'),'A0014':('volumetric energy density','615','Wh/L',None),'A0015':('gravimetric energy density','230','Wh/kg',None),'A0016':('diameter','21.55','mm','maximum'),'A0017':('height','70.15','mm','maximum'),'A0018':('weight','70','g','maximum')}
  if suffix in mapping:
   e,v,u,q=mapping[suffix];qb=[{'entity':e,'value_text':v,'unit':u,'qualifier':q}];find=['The value is in the P42A v1.7 cell/physical characteristics block; adjacent label and qualifier determine its meaning.'];cond=['Only for INR-21700-P42A product data sheet version 1.7.','Manufacturer states the information is reference-only, not a performance guarantee or warranty, and may change.'];ready=True
  else:
   role='SOURCE_FIGURE_CURVE_LABEL';amps={'A0022':'10','A0023':'20','A0024':'30'}[suffix];qb=[{'entity':'Discharge Rate Characteristics curve label','value_text':amps,'unit':'A','parameter_value':False}];find=['The current is a plotted series label in the Discharge Rate Characteristics figure, not a standalone allowable-current limit.'];cond=['P42A v1.7 Discharge Rate Characteristics figure.','Figure conditions: CC-CV charge at 4.2 A to 4.2 V with 50 mA termination; discharge cutoff 2.5 V; temperature 23 °C.','Not a general maximum current, safety threshold, or recommendation.'];ready=False
   refs.append(f'{p}#page=1&figure=Discharge_Rate_Characteristics&curve={amps}A')
 status='RESOLVED' if not unknown else 'UNRESOLVED'
 base={'fact_id':fid,'file_id':file,'source_id':'SRC-038','original_locator':c['locator'],'review_status':status,'semantic_role':role,'context_findings':find,'quantity_bindings':qb,'source_entity_and_version':entity,'conditions_and_exceptions':cond,'evidence_refs':refs,'original_unknown_resolution':{'original':'CONDITION_NOT_EXPLICIT_IN_LOCAL_SENTENCE','resolution':'Resolved from minimum adjacent page/table/header/footnote or chart context.'},'parameter_record_ready':ready,'structured_code_record_ready':role=='HAZCHEM_EMERGENCY_ACTION_CODE','current_build_use_status':'NOT_ALLOWED_FOR_LOCAL_RAG','remaining_unknowns':unknown,'reason':'Source-bound semantic meaning established; parameter_record_ready does not authorize case use, RAG, training, redistribution, or current applicability.'}
 res.append(base);ctx.append({'fact_id':fid,'file_id':file,'page':page,'checked_scope':'minimum adjacent table/header/footnote/chart context','semantic_summary':find,'restricted_source_text_persisted':False})
assert len(res)==58 and {x['fact_id'] for x in res}==ids
def dump(n,xs):
 with (OUT/n).open('w',encoding='utf-8',newline='\n') as f:
  for x in xs:f.write(json.dumps(x,ensure_ascii=False,sort_keys=True)+'\n')
dump('REVIEW_RESULTS.jsonl',res);dump('CONTEXT_EVIDENCE.jsonl',ctx);dump('UNRESOLVED.jsonl',[x for x in res if x['review_status']=='UNRESOLVED'])
checks={'scope_58':len(scope)==58,'results_58':len(res)==58,'exact_set':{x['fact_id'] for x in res}==ids,'file_counts':collections.Counter(x['file_id'] for x in res)==collections.Counter(x['file_id'] for x in scope),'required_fields':all(all(k in x for k in ['fact_id','file_id','source_id','original_locator','review_status','semantic_role','context_findings','quantity_bindings','source_entity_and_version','conditions_and_exceptions','evidence_refs','original_unknown_resolution','parameter_record_ready','current_build_use_status','remaining_unknowns','reason']) for x in res),'all_build_use_restricted':all(x['current_build_use_status']=='NOT_ALLOWED_FOR_LOCAL_RAG' for x in res),'hazchem_not_watts':all(not x['parameter_record_ready'] and x['structured_code_record_ready'] and all(q.get('unit') is None for q in x['quantity_bindings']) for x in res if x['semantic_role']=='HAZCHEM_EMERGENCY_ACTION_CODE'),'figure_labels_nonparameter':sum(x['semantic_role']=='SOURCE_FIGURE_CURVE_LABEL' for x in res)==3 and all(not x['parameter_record_ready'] and any('Figure conditions:' in c for c in x['conditions_and_exceptions']) for x in res if x['semantic_role']=='SOURCE_FIGURE_CURVE_LABEL'),'certificate_5a_not_amperes':all(q.get('unit') is None for x in res if x['semantic_role']=='CERTIFICATE_ISSUER_ADDRESS_TOKEN' for q in x['quantity_bindings']),'unresolved_matches':sum(x['review_status']=='UNRESOLVED' for x in res)==len(rows(OUT/'UNRESOLVED.jsonl'))}
out={'status':'PASS' if all(checks.values()) else 'FAIL','checks':checks,'counts':{'results':58,'resolved':sum(x['review_status']=='RESOLVED' for x in res),'unresolved':sum(x['review_status']=='UNRESOLVED' for x in res),'parameter_record_ready':sum(x['parameter_record_ready'] for x in res)},'scope':'Exact SRC-038 58 candidate bounded semantic review using minimum adjacent PDF page/table/header/footnote/chart context.','not_checked':['certificate current validity','case-time applicability','permission for RAG/training/redistribution'],'command':f'python -B {__file__}'}
(OUT/'CHECK_RESULTS.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8');(OUT/'RUN.log').write_text(datetime.datetime.now(datetime.timezone.utc).isoformat()+' PASS\n',encoding='utf-8');print(json.dumps(out))


