from __future__ import annotations
import json
from collections import Counter
from pathlib import Path
ROOT=Path(r"E:\desn 2000\bsc"); RUN=ROOT/"data_preparation/CR-EXT-DATA-001/20260920T001256_AEST"; OUT=RUN/"existing233/documents"
scope=[json.loads(x) for x in (RUN/"INPUT_SCOPE.jsonl").open(encoding="utf-8") if x.strip()]; expected={x["file_id"] for x in scope if x.get("pending67") is False and x.get("assigned_lane")=="documents"}
dec=[json.loads(x) for x in (OUT/"LOCAL_ACTION_DECISIONS.jsonl").open(encoding="utf-8") if x.strip()]; man=[json.loads(x) for x in (OUT/"PROCESSING_MANIFEST.jsonl").open(encoding="utf-8") if x.strip()]; qual=[json.loads(x) for x in (OUT/"QUALITY_FINDINGS.jsonl").open(encoding="utf-8") if x.strip()]; valid={x["requirement_id"] for x in (json.loads(z) for z in (RUN/"requirements/REQUIREMENTS.jsonl").open(encoding="utf-8") if z.strip())}
checks={"scope_38":len(expected)==38,"decisions_exact":len(dec)==38 and {x['file_id'] for x in dec}==expected,"manifest_exact":len(man)==38 and {x['file_id'] for x in man}==expected,"quality_exact":len(qual)==38 and {x['file_id'] for x in qual}==expected,"all_prepared":all(x['status']=="LOCALLY_PREPARED_WITH_REUSED_EXTRACTION" for x in man),"all_bindings_verified":all(x['basis']['verified'] and x['extraction_binding_verified'] for x in dec),"derived_exist":all(Path(p).is_file() for x in man for p in x['derived_outputs']),"requirements_valid":all(set(x['requirement_support']['requirement_ids'])<=valid for x in man),"not_module_only":all('module_ids were not used' in x['requirement_support']['basis'] for x in man),"prohibited_uses_closed":all(x['rag_status']=="NOT_ADMITTED" and x['training_status']=="NOT_AUTHORIZED" and x['external_transfer']=="NOT_AUTHORIZED_NOT_ATTEMPTED" for x in man),"three_pdf_geometry":sum('geometry_table_count' in x['profile'] for x in man)==3}
report={"status":"PASS" if all(checks.values()) else "FAIL","scope":"Existing-38 coverage, binding, artifact, requirement-ID validity and action-boundary checks only; not semantic completeness, safety authority, parameter correctness, or production readiness.","checks":checks,"quality_counts":Counter(x['quality_status'] for x in qual),"semantic_roles":Counter(x['semantic_role'] for x in man),"derived_file_count":sum(len(x['derived_outputs']) for x in man)}
(OUT/"CHECK_RESULTS.json").write_text(json.dumps(report,ensure_ascii=False,indent=2,default=dict)+"\n",encoding="utf-8"); print(json.dumps(report,ensure_ascii=False,indent=2,default=dict)); raise SystemExit(0 if report['status']=="PASS" else 1)
